### ISSUE TITLE
Update User model and user routes to work with more data

### ISSUE THREAD

**Issue by NukaGrizz** [NukaGrizz/MyAdventure#19]
Update user model table/structure

**User model**

- id   Number auto increment uniquekey
- username  String NotNull
- email  String NotNull
- password   hashed NotNull
- picture img NotNull with default value (https://www.bezkoder.com/node-js-upload-image-mysql/) combine correct parts of  this 'Define the Sequelize Model' to this value
- motto String CanBeNull
- date_of_birth  NumberorDate CanBeNull
- hometown String CanBeNull
- education  String CanBeNull
- employment   String CanBeNull
- relationship_status  String CanBeNull
- hobbies   [] CanBeNull
- freinds_ids  [] CanBeNull

**Forigenkeys added through the models index files**

Freinds(refrences user ids of freinds from freinds_ids) 
Posts(refernces post beloging to user)
Comments(refernaces comments belonging to user)
Votes(refernces votes belonging to user)

**Comment by gfernandez25** [comment]
User model and user routes updated to work with more data. All columns fields added. images added to seed data files. images hosted in cloudinary
