### ISSUE TITLE
Create post page in handlebars

### ISSUE THREAD

**Issue by NukaGrizz** [NukaGrizz/MyAdventure#39]
## Create the post page by editing the single-post.handlebars as well as the comments.handlebars and the post-info.handlebars files.

- Use the css and html styling from the Post boilerplate
- For user imgs use following till seeds fills in imgs from cloudinary now src="https://res.cloudinary.com/myadventureteam/image/upload/v1632164336/ryjaor3ui85sf5f6s0fx.jpg"

**Comment by Flying-dink** [comment]
Thank You for your help
